Study helper phase 2 update
christianjokhaji/DiscordBot pull request #39
Opened 2024-08-06 20:23 UTC by iDasher

I implemented 1-3 from the phase 2 issue, meaning I now can test the user on their questions, give a score and show them their performance compared to prior attempts at that quiz to help see if they are improving. Additionally added javadoc to many methods and more testing.

2024-08-06 21:45 UTC, xinyue296 commented on .gitignore
> +### Storing files ###
is this the correct path?

2024-08-06 21:48 UTC, xinyue296 requested changes
Thank you for the hard work! Good job on testing!

2024-08-07 00:40 UTC, Overpoweredplatypus approved these changes
Excellent

2024-08-07 02:55 UTC, xinyue296 approved these changes

2024-08-07 03:22 UTC, sailoraria approved these changes
Looks good!

2024-08-07 03:22 UTC, merged