Removed all comments and added some more javadoc
christianjokhaji/DiscordBot pull request #46
Opened 2024-08-12 18:38 UTC by iDasher

2024-08-13 15:37 UTC, xinyue296 approved these changes
Looks good to me! Thanks so much for all your hard work on the project 👏

2024-08-14 15:31 UTC, Overpoweredplatypus approved these changes

2024-08-18 18:39 UTC, sailoraria requested changes
looks good, i think you need javadoc for the rest of the public methods in your entities (e.g the getters because they return values). also some of your java doc for the methods in the data access and use case interactors dont contain summary sentences and just have the tags which i think would be important to include

2024-08-18 21:04 UTC, sailoraria approved these changes
thank you for considering my feedback!

2024-08-18 21:05 UTC, merged